# Generated by Django 5.2.7 on 2025-11-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnvase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_cajas', models.PositiveIntegerField(default=0)),
                ('peso_neto', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.productor')),
                ('tipo_envase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.tipoenvase')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.variedad')),
            ],
        ),
    ]
