# Generated by Django 5.2.7 on 2025-11-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='enfriado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pallet',
            name='fumigado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pallet',
            name='pre_procesos',
            field=models.BooleanField(default=False),
        ),
    ]
