# Generated by Django 5.2.7 on 2025-11-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_pallet_enfriado_pallet_fumigado_pallet_pre_procesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pallet',
            name='organico',
            field=models.BooleanField(default=False),
        ),
    ]
