# Generated by Django 5.2.7 on 2025-11-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_pallet_bloqueado_pallet_organico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
    ]
