# Generated by Django 5.2.7 on 2025-11-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_pallet_procesado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoProceso',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.productor')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.variedad')),
            ],
        ),
        migrations.AddField(
            model_name='pallet',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packing.grupoproceso'),
        ),
    ]
