# Generated by Django 5.2.7 on 2025-11-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_grupoproceso_pallet_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='bloqueado',
            new_name='bloqueado_proceso',
        ),
        migrations.AddField(
            model_name='pallet',
            name='bloqueado_recepcion',
            field=models.BooleanField(default=False),
        ),
    ]
