# Generated by Django 5.2.7 on 2025-11-07 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_rename_bloqueado_pallet_bloqueado_proceso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPocillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PalletTerminado',
            fields=[
                ('id_pallet', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_cajas', models.PositiveIntegerField()),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.distribuidor')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.linea')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.variedad')),
                ('tipo_pocillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.tipopocillo')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cajas', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.distribuidor')),
                ('grupo_proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packing.grupoproceso')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.linea')),
                ('tipo_pocillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.tipopocillo')),
            ],
        ),
    ]
