# Generated by Django 5.2.7 on 2025-11-07 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0007_distribuidor_linea_tipopocillo_palletterminado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQFDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_iqf', models.DecimalField(decimal_places=1, max_digits=6)),
                ('peso_descarte', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('grupo_proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packing.grupoproceso')),
            ],
        ),
    ]
