# Generated by Django 5.2.7 on 2025-11-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0008_iqfdescarte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palletterminado',
            name='id_pallet',
        ),
        migrations.RemoveField(
            model_name='palletterminado',
            name='variedad',
        ),
        migrations.AddField(
            model_name='palletterminado',
            name='calidad',
            field=models.CharField(choices=[('Rechazado', 'Rechazado'), ('Baja', 'Baja'), ('Buena', 'Buena'), ('Excelente', 'Excelente')], default='Baja', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palletterminado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipopocillo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='GrupoTerminado',
        ),
    ]
