# Generated by Django 5.2.7 on 2025-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0009_remove_palletterminado_id_pallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletterminado',
            name='estado',
            field=models.CharField(choices=[('Por enviar', 'Por enviar'), ('Enviado', 'Enviado')], default='Por enviar', max_length=20),
        ),
    ]
