# Generated by Django 5.2.7 on 2025-11-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0010_palletterminado_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iqfdescarte',
            old_name='fecha_registro',
            new_name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='iqfdescarte',
            name='estado',
            field=models.CharField(choices=[('EN_IQF', 'En IQF'), ('RETIRADO', 'Retirado')], default='EN_IQF', max_length=20),
        ),
        migrations.AddField(
            model_name='iqfdescarte',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iqfdescarte',
            name='peso_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iqfdescarte',
            name='productor',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iqfdescarte',
            name='variedad',
            field=models.CharField(default='Desconocida', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iqfdescarte',
            name='peso_descarte',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='iqfdescarte',
            name='peso_iqf',
            field=models.FloatField(),
        ),
    ]
