# Generated by Django 5.2.7 on 2025-11-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0011_rename_fecha_registro_iqfdescarte_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletterminado',
            name='variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.variedad'),
        ),
    ]
