# Generated by Django 5.2.7 on 2025-11-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0012_palletterminado_variedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqfdescarte',
            name='estado',
            field=models.CharField(choices=[('EN_IQF', 'En IQF'), ('RETIRADO', 'Retirado'), ('DESPACHADO', 'Despachado')], default='EN_IQF', max_length=20),
        ),
    ]
