# Generated by Django 5.2.7 on 2025-12-19 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0014_registroactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='accion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='modulo',
            field=models.CharField(max_length=100),
        ),
    ]
